---
- name: List os families
  debug:
    var: ansible_os_family
#- name: Gather OS specific varibles
#  include_vars: "{{ item }}"
#  with_first_found:
#      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#      - "{{ ansible_distribution }}.yml"
#      - "{{ ansible_os_family }}.yml"
- include_tasks: "{{ ansible_os_family }}.yml"
