---
- name: OS update
  hosts: all
  gather_facts: yes
  become: true
  roles:
    - name: user
      tags: [user]

    - name: os_update
      tags: [update]

    - name: prometheus
      tags: [prometheus]

- name: install monitoring stack
  hosts: monitorserver
  tags: [monitoring]
  become: yes
  roles:
    - name: prometheus
      vars:
        prometheus_node_exporter_group: nodeservers


- name: install node-exporter
  hosts: nodeservers
  tags: [node_exporter]
  become: yes
  roles:
    - name: node_exporter
