
- name: ensure group "nopw_admin" exists
  group:
    name: nopw_admin
    state: absent

- name: "Creat users"
  user:
    name: "{{ name }}"
    shell: /usr/bin/bash
    state: present

- name: "Add public"
  authorized_key:
    user: "{{ name }}"
    key: "{{ lookup('file', publicKeyPath) }}"


- name: Allow user to use sudo without password
  lineinfile:
    path: "/etc/sudoers.d/{{ item.name }}-nopw"
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    create: yes
